# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            grahana
tagline:          'grahanae'
description:      'Resurrected blog of Pavan K Murthy: Thoughts on stuff.'
url:              http://p6.github.io
baseurl:          /

author:
  name:           'Pavan K Murthy'
  url:            https://twitter.com/p6

paginate:         5

# Custom vars
version:          2.1.0

github:           http://github.com/p6
