# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            grahana
tagline:          'Pavan Keshavamurthy - Hacker, Slacker, Backpacker'
description:      'Resurrected blog of Pavan K Murthy; Thoughts on stuff.'
url:              http://grahana.net
baseurl:          http://grahana.net/

author:
  name:           'Pavan K Murthy'
  url:            https://twitter.com/p6

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:           http://github.com/p6
